/*
 * This source file was generated by the Gradle 'init' task
 */
package com.engineeringDigest.vehicles;

public class MyApp {


    public static void main(String[] args) {



//        Vehicle vehicle=new Car();
//
//        String mileage=vehicle.getMileage();
//
//        System.out.println(mileage);


        System.out.println(100/0);


    }
}



