/*
 * This source file was generated by the Gradle 'init' task
 */
package com.engineeringDigest.vehicles;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        MyApp classUnderTest = new MyApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
